#!/usr/bin/env node

const { readFileSync } = require('fs');
const { kml2geojson } = require('./kml2geojson.js');

const file = readFileSync(0)?.toString('utf-8');

const geojson = kml2geojson(file);
console.log(JSON.stringify(geojson, null, 2));
