#!/usr/bin/env node

const { readFileSync } = require('fs');
const { parse } = require('wkt');

var wkt = readFileSync(0)?.toString('utf-8');
const data = parse(wkt);
const geojson = JSON.stringify(data, null, 2);

console.log(geojson);
